// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwpMLBhQHNd7FUEqKIIMGUf74r5IDNdSc',
    appId: '1:798135480254:web:fc00fcec4c8acad78593ef',
    messagingSenderId: '798135480254',
    projectId: 'sahayk-b7616',
    authDomain: 'sahayk-b7616.firebaseapp.com',
    storageBucket: 'sahayk-b7616.firebasestorage.app',
    measurementId: 'G-RVV27MVZ7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_oxPRW1mZhQebvHrWqtSBMVjexBjBEkc',
    appId: '1:798135480254:android:2a524d07cd2d13138593ef',
    messagingSenderId: '798135480254',
    projectId: 'sahayk-b7616',
    storageBucket: 'sahayk-b7616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVOTyaENtSQe6sKWYzPMgj1teoFnIjTro',
    appId: '1:798135480254:ios:e3824ef956d647378593ef',
    messagingSenderId: '798135480254',
    projectId: 'sahayk-b7616',
    storageBucket: 'sahayk-b7616.firebasestorage.app',
    iosClientId: '798135480254-om72itf7hudt4dn5ota81j5e2g5ntakh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVOTyaENtSQe6sKWYzPMgj1teoFnIjTro',
    appId: '1:798135480254:ios:e3824ef956d647378593ef',
    messagingSenderId: '798135480254',
    projectId: 'sahayk-b7616',
    storageBucket: 'sahayk-b7616.firebasestorage.app',
    iosClientId: '798135480254-om72itf7hudt4dn5ota81j5e2g5ntakh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahayak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwpMLBhQHNd7FUEqKIIMGUf74r5IDNdSc',
    appId: '1:798135480254:web:b0507be0542273338593ef',
    messagingSenderId: '798135480254',
    projectId: 'sahayk-b7616',
    authDomain: 'sahayk-b7616.firebaseapp.com',
    storageBucket: 'sahayk-b7616.firebasestorage.app',
    measurementId: 'G-6YGTW1PMPR',
  );

}