name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

env:
  PROJECT_ID: sahayak-mvp-466309
  SERVICE_NAME: sahayak-backend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # This is the correct way to authenticate
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Build and Deploy
      run: |
        cd backend
        
        # Deploy to Cloud Run
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --memory 1Gi \
          --cpu 1 \
          --timeout 300 \
          --max-instances 10 \
          --set-env-vars "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" \
          --project ${{ env.PROJECT_ID }}

    - name: Get Service URL
      if: success()
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --format 'value(status.url)' \
          --project ${{ env.PROJECT_ID }})
        
        echo "Service deployed at: $SERVICE_URL"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

    - name: Test Deployment
      if: success()
      run: |
        echo "Testing health endpoint..."
        curl -f "${{ env.SERVICE_URL }}/health" || echo "Health check failed (might be normal if endpoint doesn't exist)"